### ISSUE TITLE
Integration with 1Password Desktop App Instead of Service Account

### ISSUE THREAD

**Issue by reonokiy** [mrjones2014/opnix#7]
The op cli can integrate with the 1Password desktop app for authentication on local systems. This project currently uses a service account for authentication. Is it possible to integrate directly with the desktop app instead, eliminating the need for a service account?

**Comment by mrjones2014** [comment]
It's potentially possible, but the main use case is for headless servers. I've also run into issues with CLI other than a globally installed one integrating with the desktop app correctly.

**Comment by dzervas** [comment]
won't the opnix service timeout after some time (as you need to boot, login and then unlock 1password gui)?
also you need some kind of op socket translation so that the systemd service (running as root) can communicate with the local user socket

**Comment by mrjones2014** [comment]
Yeah, there are a lot of issues with this approach; now that you mention it, you're right, it would block the boot process. It theoretically could work for rebuilds when you're already booted and 1Password GUI is already running. But it will block boot process.

Closing as `wontfix`, sorry.
